### PR TITLE
Resolves #6

### LINKED ISSUE #6: Prompt for number
Is it ever really valuable to exec into the very first container listed in your namespace? Currently you have a 1/N chance with `kex`. Otherwise, you again type `kex -n <NUM> [OPTIONS]`. What if we instead make `kex` default to `--list`, and prompt for a number (it can still default to 1 if you hit enter with no number). Worst case you type one extra key… normal case, you save 8 keys (plus any addtl options). Thoughts?

### PR DESCRIPTION
**Pull request by scottrigby**

### CODE REVIEW

**Comment by lypht** [comment]
LGTM

**Comment by scottrigby** [comment]
@lypht OK so, paraphrasing my notes from Slack - I added this functionality to the PR:

In this PR, the flagless `kex` command prompts for the all flags with defaults. Example:
```bash
$ kex

Namespace? (default qux):

Pod number? (default 1):
    1 foo-drupal
    2 bar-mariadb
    3 baz-alpine
2

Command? (default bash)
mysql

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 16265
Server version: 10.1.23-MariaDB Source distribution

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

**Comment by lypht** [comment]
I like this even better.  Good work!

**Comment by scottrigby** [comment]
@lypht new asciinema?

**Pull request merged**
